# Generated by Django 4.2.4 on 2023-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lat", models.FloatField(blank=True, default=47.1513451, null=True)),
                ("lng", models.FloatField(blank=True, default=-126.1665193, null=True)),
            ],
        ),
    ]
